### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by IsraaSulaiman** [FACG6/logicteca#48]
**File Structure**

1. client
  - components
    - common components
      - search
         - index.jsx
         - style.css
    - layout
       - header
          - index.jsx
          - style.css
     - login
      - userForm
        - index.jsx
        - style.css
      - about
        - index.jsx
        - style.css
    - projects
        - index.jsx
        - style.css
        - project
           - index.jsx
           - style.css
        - newProject
           - index.jsx
           - style.css

    - members
        - index.jsx
        - style.css
       - scrum
         - index.jsx
         - style.css
        
2. server
  - controllers
      - index.js
      - login.js
      - logout.js
      - members.js
      - projects.js
      - scrums.js
      - tasks.js
     - middlewares
 
  - database
    - config
      - dbConnection.js
      - dbBuild.js
      - dbBuild.sql
   - queries
     - members
        - selectMembers.js
        - insertMember.js
        - updateMember.js
        - deleteMember.js
     - projects
        - selectProjects.js
        - insertProject.js
        - updateProject.js
        - deleteProject.js
     - scrums
        - selectScrums.js
        - insertScrum.js
        - updateScrum.js
        - deleteScrum.js
     - tasks
        - selectTasks.js
        - insertTask.js
        - updateTask.js
        - deleteTask.js

  - utilits
       - hashPassword.js
       - createToken.js

 - app.js
 - index.js

3.Test
  - testClient
  - testServer

**Comment by AymanAlqoqa** [comment]
I think projects should include any component related to it.

like this
- projects
   - index.jsx
   - style.css
   * project
         * index.jsx
         ....
