### ISSUE TITLE
Indent  Issue

### ISSUE THREAD

**Issue by IsraaSulaiman** [FACG6/logicteca#76]
I have indent issue. The indentation in my vs code is 2 tab size but when I do a pull request, I notice that there is too much tab indentation. 

**Here is my vs code setting.json:**
![Screenshot from 2019-04-19 16-44-27](https://user-images.githubusercontent.com/35868173/56426888-8705ea00-62c2-11e9-9e79-8b6ee3991d8a.png)

@ashatat @AymanAlqoqa @aminalakhsham

**Comment by ashatat** [comment]
@IsraaSulaiman  whenever you have time, let's do a TeamViewer session and try to solve it together

**Comment by IsraaSulaiman** [comment]
I solved it. Prettier extension causes this problem @ashatat

**Comment by ashatat** [comment]
If it is resolved, then close the issue, please :pray:
